import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import SideBar from 'src/components/layouts/SideBar';

import './globals.css';

import Authentication from 'src/components/provider/Authentication';
import ReactQueryProvider from 'src/components/provider/ReactQuery';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Authentication>
            <SideBar />
            {children}
          </Authentication>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
